# MICLAUS GENERAL PUBLIC SOFTWARE LICENSE
Copyright (c) 2022 Miclaus Industries Corporation B.V.

Version 1.0, April 2O22

IMPORTANT: THIS SOFTWARE PRODUCT IS SUPPLIED TO YOU BY MICLAUS INDUSTRIES CORPORATION B.V. ("MICLAUSCORP") IN CONSIDERATION OF YOUR AGREEMENT TO THE FOLLOWING TERMS, AND YOUR DOWNLOAD, USE, INSTALLATION, MODIFICATION OR REDISTRIBUTION OF THIS SOFTWARE PRODUCT CONSTITUTES ACCEPTANCE OF THESE TERMS. IF YOU DO NOT AGREE WITH THESE TERMS, PLEASE DO NOT DOWNLOAD, USE, INSTALL, MODIFY OR REDISTRIBUTE THIS SOFTWARE PRODUCT.

1. Permission is hereby granted, either free of charge or licensed, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

2. The title and intellectual property rights to any content displayed by, generated by, made by, or accessed through the MiclausCorp software belongs to the respective content owner. Such content may be protected by copyright and/or other intellectual property laws and treaties and may be subject to terms of use of the third party providing such content. Except as otherwise provided herein, this License does not grant you any rights to use such content nor does it guarantee that such content will continue to be available to you.

3. This license is effective until terminated. Your rights under this license will terminate automatically or otherwise cease to be effective without notice from Miclaus Industries Corporation B.V. if you fail to comply with any term(s) of this License. Upon the termination of this License, you shall cease all use of the Miclaus Industries Corporation B.V. products and destroy all copies, full or partial, of the product.

4. You further acknowledge that, unless specifically noted, the products, software, and services are not intended or suitable for use in situations or environments where the failure and/or time delays of, and/or errors and/or inaccuracies in the content, data, or information provided by the software or services could lead to death, personal injury, or severe physical or environmental damage, including without limitation the operation of nuclear facilities, aircraft navigation or communication systems, air traffic control, life support or weapons systems.

5. In no event shall MiclausCorp be liable for any special, indirect, incidental or consequential damages arising in any way out of the use, reproduction, modification and/or distribution of the MiclausCorp software, however caused and whether under theory of contract, tort (including negligence), strict liability or otherwise, even if MiclausCorp has been advised of the possibility of such damage.

6. Miclaus Industries Corporation B.V., at its discretion, may make available future "upgrades" or "updates" to the Miclaus Industries Corporation B.V. products. Unless otherwise noted, you are free to use an older version of the Miclaus Industries Corporation B.V. software without upgrading, however, support and/or availability of services may become limited.

7. This license does not override any applicable existing copyright or contract law in your nation, it rather appends to them.

8. Unless otherwise noted, This content is not affiliated with, endorsed, sponsored, or specifically approved by the targeted platform's parent company (eg. Apple Inc. for software targeting Apple platforms specifically) and is not responsible for it. For more information see their content policies.

9. You agree that you (and only you) are liable for any content you may produce using Miclaus Industries Corporation B.V. products.

10. While this software may be bundled, subjected to, and/or shipped with a version of this license, Unless otherwise specified, Miclaus Industries Corporation B.V. Software will always be subject to the latest available version of this license, with or without upgrading.

THE SOFTWARE PRODUCT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Copyright (c) 2022 Miclaus Industries Corporation B.V. All rights reserved.